---
title: "Git configuration"
format:
  html:
    embed-resources: true
editor: visual
---

## Git configuration

1.  Edit the code chunk below replace the placeholders with your name and email address (these will be the details that git will use to identify you when you commit changes to the repository). Ensure to keep the quotation marks (e.g. "rainbow-train")
2.  Render the document

```{r}
library(usethis)
use_git_config(user.name = "Your Name", user.email = "Your Email")
```

## Commit and push your changes

1.  Navigate to the Git pane in the top-right window
2.  Check the box next to the git-configuration.qmd file to stage it for commit
3.  Click on the "Commit" button
4.  Enter a commit message in the "Commit message" field
5.  Click on the "Commit" button
6.  Click on the "Push" button
7.  Enter your GitHub username and GitHub Personal Access Token (PAT) in the "Username" and "Password" fields

**Important:** You need to enter the GitHub Personal Access Token (PAT) in the Password field, not your password for GitHub.

## Open an issue on GitHub

1.  Open [github.com](https://github.com/) in your browser.
2.  Navigate to the GitHub organisation for the course.
3.  Find the repository git-configuration that ends with your GitHub username.
4.  Click on the "Issues" tab.
5.  Click on the green "New issue" button.
6.  In the "Title" field write: "Completed git configuration".
7.  In the "Leave a comment" field, tag the course instructor @larnsce
